ShowDownWestern/ShowDownWestern/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from WestApp import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.homepage,name='index'),
    url(r'^upload/',include('WestApp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ShowDownWestern/WestApp/urls.py
from django.conf.urls import url
from WestApp import views

app_name = 'WestApp'

urlpatterns = [
    url(r'^$',views.upload,name='upload'),
]

ShowDownWestern/WestApp/models.py
from django.db import models
from django.urls import reverse
from imagekit.models import ImageSpecField,ProcessedImageField
from imagekit.processors import ResizeToFill,ResizeToFit,SmartResize,Transpose,ResizeToCover,Thumbnail,SmartCrop

# Create your models here.

class ImageModel(models.Model):
    caption = models.CharField(max_length=32)
    #image = models.ImageField(upload_to='media/')

    image = ProcessedImageField(upload_to='media',
                                 processors=[Transpose(),SmartResize(550,550)],
                                 format='JPEG',
                                 options={'quality':90},null=True
                                )

    upload_date = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('index')

    def __str__(self):
        return self.caption

ShowDownWestern/WestApp/forms.py
from django import forms
from WestApp.models import ImageModel

class ImageForm(forms.ModelForm):
    class Meta:
        model = ImageModel
        fields = "__all__"

ShowDownWestern/WestApp/views.py
from django.shortcuts import render
from WestApp.models import ImageModel
from WestApp.forms import ImageForm
from django.http import HttpResponseRedirect

# Create your views here.
def homepage(request):
    query_get_images = ImageModel.objects.order_by('-caption')
    context = {"images":query_get_images}
    return render(request,'index.html',context)

def upload(request):
    if request.method == "POST":
        form = ImageForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/")
    else:
        form = ImageForm()
    context = {"form":form}
    return render(request,'upload.html',context)

ShowDownWestern/templates/base.html
<!Doctype html>
{% load static %}
{% load imagekit %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="A Cool new site">
    <meta name="author" content="JackermanX">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet">
  </head>

  <body>


    <main role="main">
      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
            <img src="{% static 'images/Westar.png' %}" class="img-fluid" alt="Responsive image" height="560" width="560"/>
        </div>
      </div>
    </main>
    {% block body %}
    {% endblock %}

    <footer class="footer">
      <p>&copy; A JackermanX project 2018</p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  </body>
</html>

ShowDownWestern/templates/index.html
{% extends 'base.html'%}

{% block title %}home{% endblock %}

{% block body %}
<p class="welcome">Welcome! to the Selfie site feel free to upload your awesome selfie and tell yours friends about it.<br>Check out what they have uploaded.</p>

<div class="upload">
    <em>Upload yours here.</em><br>
    <a href="{% url 'WestApp:upload'%} " class="btn btn-primary">Upload</a>
</div>

<div class="container">
    {% if images %}
        <div class="row">
        {% for img in images %}
                <div class="col-md-6">
                    <span class="me">{{img.caption}}</span><br>
                    <img src="media/{{img.image}}" alt="cool pic here" width="500" height="500"><br>
                    {{img.upload_date|timesince}} ago<br>
                </div>

        {% endfor %}
            </div>
    {% else %}
        <p>it's lonely here. click the upload button to upload</p>
    {% endif%}

</div>
{% endblock %}

ShowDownWestern/templates/oldBase.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

</head>

<body>

<div class="jumbotron">
        <img src="{% static 'images/iconround.png' %}" class="img-fluid" alt="Responsive image" height="220" width="220"/>
    <main role="main" class="container">

          <div class="starter-template">

              <h1>Western<br> <em>SELFIE</em> <br>Showdown</h1>

          </div>

    </main>

</div>

{% block body %}
{% endblock %}



</body>
</html>

ShowDownWestern/templates/upload.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}

{% block title %}upload{% endblock %}

{% block body %}
<div class="uploadpage">
    <form method="POST" enctype="multipart/form-data" action="{% url 'WestApp:upload' %}">
        {% csrf_token %}
        <div class="uploadform">
            <p>32 characters</p>
            {{form|crispy}}
        </div>
        <input type="submit" value="upload" class="btn btn-primary">
    </form>
    <br>
    <a href="{% url 'index' %}" >homepage</a>
</div>


{% endblock %}